### ISSUE TITLE
TypeError: object with buffer protocol required on widows

### ISSUE THREAD

**Issue by erleto74** [NikodemBartnik/Pico-Plotter#1]
Hello,
I have an error when trying to testing this project. Can you help me how to solve this problem?
![image](https://user-images.githubusercontent.com/114717034/193963785-09f10651-79ca-46ac-8384-46fad6254907.png)
I test it in win 10 with thonny ver 4.0.0

**Comment by NikodemBartnik** [comment]
You should run this code on Pi Pico, not your windows machine

**Comment by erleto74** [comment]
Thank you, I was wrong.
